apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java-app
spec:
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 300
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: us.gcr.io/theonlydavidlee-work-1/demo-java-app
        imagePullPolicy: IfNotPresent
        name: demo-java-app
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - containerPort: 8080
          name: http
